In [2]:
import numpy as np

# 逻辑运算

In [10]:
stock_change=np.random.normal(0,1,(8,10))
stock_change

array([[ 0.92734192,  1.74724398, -0.4591395 , -0.38826131,  0.70415724,
         0.75658673,  0.11598324,  1.97998045,  1.06613085,  1.19581041],
       [ 0.34345517,  0.43627709, -1.05268756, -0.57782308,  2.97232362,
        -0.95077058,  1.51311826, -1.38770297,  0.02797954, -0.32309498],
       [ 0.149272  , -0.51020593, -0.12267105,  0.95785477, -1.77383082,
         1.11387819, -1.68342161,  0.67008831, -1.09897752,  0.53804595],
       [ 0.80693768,  0.62496037, -0.40051867, -0.82906962,  0.35797353,
        -0.00458285, -1.42130049, -0.46162983, -0.22646213,  0.36602477],
       [-0.87285471, -0.22971333, -1.66328658,  2.19328267,  0.7463275 ,
         0.70196473,  0.94336252, -0.95709971, -0.77821873, -1.0463661 ],
       [ 0.05554732,  0.97839213, -0.32649028,  0.86416856, -1.01597683,
        -0.34487223, -0.21219342,  1.2773467 , -1.02767268, -0.17520231],
       [ 0.29298336,  0.63274925,  0.86324219,  0.22427574, -1.0084398 ,
         0.39575355,  0.49501133, -0.49168933

In [11]:
stock_c=stock_change[0:5,0:5]
stock_c

array([[ 0.92734192,  1.74724398, -0.4591395 , -0.38826131,  0.70415724],
       [ 0.34345517,  0.43627709, -1.05268756, -0.57782308,  2.97232362],
       [ 0.149272  , -0.51020593, -0.12267105,  0.95785477, -1.77383082],
       [ 0.80693768,  0.62496037, -0.40051867, -0.82906962,  0.35797353],
       [-0.87285471, -0.22971333, -1.66328658,  2.19328267,  0.7463275 ]])

In [12]:
stock_c>1

array([[False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [15]:
stock_c[stock_c>1]=2

In [16]:
stock_c

array([[ 0.92734192,  2.        , -0.4591395 , -0.38826131,  0.70415724],
       [ 0.34345517,  0.43627709, -1.05268756, -0.57782308,  2.        ],
       [ 0.149272  , -0.51020593, -0.12267105,  0.95785477, -1.77383082],
       [ 0.80693768,  0.62496037, -0.40051867, -0.82906962,  0.35797353],
       [-0.87285471, -0.22971333, -1.66328658,  2.        ,  0.7463275 ]])

In [24]:
stock_d=stock_change[0:2,0:3]
stock_d

array([[ 0.92734192,  2.        , -0.4591395 ],
       [ 0.34345517,  0.43627709, -1.05268756]])

In [20]:
np.all(stock_d>0)

False

In [21]:
np.any(stock_d>0)

True

In [22]:
np.where(stock_d>0,1,0)

array([[1, 1, 0],
       [1, 1, 0]])

In [23]:
np.where(np.logical_and(stock_d>-0.5,stock_d<0.5),1,0)

array([[0, 0, 1],
       [1, 1, 0]])

In [25]:
np.where(np.logical_or(stock_d>0,stock_d<-1),2,0)

array([[2, 2, 0],
       [2, 2, 2]])

# 统计计算

In [28]:
stock_d.max(axis=0)

array([ 0.92734192,  2.        , -0.4591395 ])

In [29]:
stock_d.argmax()

1

In [30]:
stock_d.argmin()

5

In [34]:
arr=np.array([1,2,3,4])

In [32]:
arr+1#广播机制

array([2, 3, 4, 5])

In [35]:
arr2=np.array(range(4))
arr2

array([0, 1, 2, 3])

In [37]:
arr+arr2

array([1, 3, 5, 7])

In [38]:
np.dot(arr,arr2.T)

20